version: "3"

x-base: &default-settings
  build: .
  user: user
  ipc: host
  volumes:
    - ~:/home/user
    - ${PWD}:/app
  working_dir: /app

services:
  main:
    <<: *default-settings
    command: "/bin/bash"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - device_ids: ['0', '1']
            capabilities: ["gpu"]
  
  lab:
    <<: *default-settings
    ports:
      - 8888:8888
    command: "jupyter-lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root --ServerApp.token='' --ServerApp.password=''"
    deploy:
      resources:
        reservations:
          devices:
          - device_ids: ['0']
            capabilities: ["gpu"]

  
  tensorboard:
    <<: *default-settings
    ports:
      - 6006:6006
    command: "tensorboard --logdir . --port 6006 --host '0.0.0.0'"

